language: python
python: 3.7

dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
matrix:
  include:
    - python: 3.8
    - python: 3.7
    - python: 3.6
    - python: 3.5
    - python: 2.7

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_success: never
    on_failure: always